# Generated by Django 5.2.7 on 2025-10-21 02:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(blank=True, help_text='Número de recibo único generado automáticamente', max_length=50, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago en soles (S/)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Tarjeta de Débito'), (3, 'Tarjeta de Crédito'), (4, 'Transferencia Bancaria'), (5, 'Yape/Plin')], help_text='Método utilizado para realizar el pago')),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Completado'), (3, 'Rechazado'), (4, 'Reembolsado')], default=2, help_text='Estado actual del pago')),
                ('concepto', models.CharField(blank=True, help_text='Concepto o descripción del pago', max_length=200, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el pago', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(help_text='Administrador que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(help_text='Socio que realiza el pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
                'indexes': [models.Index(fields=['-fecha_pago'], name='pagos_fecha_p_1143cf_idx'), models.Index(fields=['socio', '-fecha_pago'], name='pagos_socio_i_2eb27b_idx'), models.Index(fields=['metodo_pago'], name='pagos_metodo__1ec5a9_idx'), models.Index(fields=['estado'], name='pagos_estado_79b102_idx')],
            },
        ),
    ]
