# Generated by Django 5.2.7 on 2025-10-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.IntegerField(choices=[('Administrador', 1), ('Usuario', 2), ('Recepcionista', 3)]),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
