# Generated by Django 5.2.7 on 2025-10-16 22:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Entrada')),
                ('metodo_registro', models.CharField(choices=[('MANUAL', 'Búsqueda Manual'), ('QR', 'Código QR')], default='MANUAL', max_length=20, verbose_name='Método de Registro')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
