# Generated by Django 5.2.7 on 2025-10-23 03:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de membresía (ej: Básica, Premium, Gold)', max_length=100, unique=True)),
                ('duracion_dias', models.IntegerField(choices=[(30, 'Mensual (30 días)'), (90, 'Trimestral (3 meses)'), (180, 'Semestral (6 meses)'), (365, 'Anual (12 meses)')], default=30, help_text='Duración de la membresía en días')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de la membresía en soles (S/)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción y beneficios de la membresía')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tipo de membresía está activo y disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Membresía',
                'verbose_name_plural': 'Tipos de Membresías',
                'ordering': ['precio', 'duracion_dias'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la membresía')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de la membresía')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la membresía está activa actualmente')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o notas sobre la membresía')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('socio', models.ForeignKey(help_text='Socio al que pertenece la membresía', on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='socios.socio')),
                ('tipo_membresia', models.ForeignKey(help_text='Tipo de membresía asignada', on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='membresias.tipomembresia')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['socio', 'activa'], name='membresias__socio_i_09db1e_idx'), models.Index(fields=['fecha_fin', 'activa'], name='membresias__fecha_f_d44f0c_idx')],
            },
        ),
    ]
